---
title: Getting Started
order: 26
---

## Self-Guided Learning About Ecological Forecasting & Dynamics

There are two primary sets of information on this site:

1. The background and conceptual foundation for ecological forecasting and dynamics, which focuses on reading and engaging with the primary scientific literature.
2. The computational tools for working with, modeling, and making forecasts from (mostly time-series) data.

The original design of this course material is that two sets of information are taught in the integrated manner shown on the [Schedule page](../schedule/index.qmd).
Where possible the conceptual material is paired with related material in R.

While taking a self-guided approach to the material you can either follow this general approach by following the order of the [Schedule page](../schedule/index.qmd) or choose to focus on either of the components in isolation.

### Self-Guided Learning - Conceptual Material

For the background and conceptual material we recommend that self-guided learners first read the Discussion Questions page for the lesson to get an idea of what they should be learning from the paper.
Then read the paper itself, trying to develop your own answers to the Discussion Questions.
Finally read through the Instructors Notes page for the lesson to see what we thought were the key take homes from the paper.
Don't worry if you didn't get all of them yourself, that's part of the learning process.

### Self-Guided Learning - R Material

The R material is generally sequential with most lessons building on previous lessons.
As such we recommend following the R material in the order present on the [Schedule page](../schedule/index.qmd).

To start an R lesson go the the Material page for the lesson to find any data or packages you will need for the tutorial. 
The R material is available in two formats - written notes and video.
We recommend choosing the format you prefer and following along with the tutorial by typing and running the code yourself each step of the way.
There are also periodic stopping points to allow learners to practice the material on their own.
We recommend stopping at these points, trying the exercise, and then proceeding to see if your approach matches those present in the notes and videos.
Once you've finished the tutorial it can be useful to practice the approaches learned on your own data or another similar dataset.

## Teaching Ecological Forecasting & Dynamics

All of the code, lesson content, data, and infrastructure for this site is openly licensed so you can use any of it in your own courses.

Lesson material can be accessed from this website or using the raw markdown files in the associated [GitHub repository](https://github.com/weecology/forecasting-course).
The core lesson material is stored in the [`lessons` directory](https://github.com/weecology/forecasting-course/tree/main/lessons) of the GitHub repository and each lesson is stored in it's own named subdirectory.

There are three general approaches to using the material in teaching:

1. Use the existing website by linking to one or more lessons from your course site and reading the associated instructors material
2. Copy material from either the website or this GitHub repository and place it on your own site. You can modify this version however you would like (or leave it unchanged), just provide a link back to the original version for attribution.
3. Create a copy of the full website and (optionally) modify the lessons and/or change which lessons are included. More information on how to do this is provided below.

### Creating a Copy of the Course Website

The course website is built with [Quarto](https://quarto.org/) and needs only Quarto and R installed.
R is used solely to regenerate the schedule table before each render, using base R with no packages.
The R code in the tutorials is displayed rather than executed, so you do not need any of the tutorial packages to build the site.

#### Netlify

The easiest way to create your own version of the course is to deploy it on Netlify. You need a GitHub account to do this.

Fork [the repository](https://github.com/weecology/forecasting-course) into your GitHub account, then [add it as a new site on Netlify](https://docs.netlify.com/welcome/add-new-site/).
The site is rendered by GitHub Actions rather than by Netlify, so you also need to set two repository secrets in GitHub: `NETLIFY_AUTH_TOKEN` (a Netlify personal access token) and `NETLIFY_SITE_ID` (the site's "API ID" in Netlify's site settings).

You can then edit files in the GitHub repository and they will automatically deploy to the website.

Edit `repo-url` in `_quarto.yml` to match the new repository you created.
This will ensure that the `Edit this page` links on each page direct you to your version of the material.

#### Locally

Install [Quarto](https://quarto.org/docs/get-started/) (1.8 or newer) and [R](https://cloud.r-project.org/), then clone the site:

```sh
git clone https://github.com/weecology/forecasting-course.git
cd forecasting-course
```

You can preview the site locally, with live reload as you edit, using:

```sh
quarto preview
```

To build the site into the `_site` directory instead, use:

```sh
quarto render
```

### Modifying the Site

* Most content is stored in one folder per lesson in the [`lessons` folder](https://github.com/weecology/forecasting-course/tree/main/lessons)
* To add a new lesson make a copy of the [lesson template folder](https://github.com/weecology/forecasting-course/tree/main/lessons/LessonTemplate), modify the pages in the resulting folder using [markdown](https://www.markdownguide.org/), and add the lesson to the `sidebar` section of `_quarto.yml`
* To modify a lesson edit the `.qmd` files in that lesson folder with the appropriate name. If you followed the instructions on installing on Netlify above, the easiest way to do this is to go to the page you want to edit on the deployed site and click the `Edit this page` link.
* To modify the schedule edit [`schedule/schedule.csv`](https://github.com/weecology/forecasting-course/blob/main/schedule/schedule.csv). The table on the Schedule page is regenerated automatically on every render, and a lesson title that doesn't match a real lesson fails the build. Each row is a date plus either a lesson title (with `kind` set to `lesson`, which must match that lesson's `title:` exactly) or a one-off event such as a project work day (with `kind` set to `event`).

### Contributing

Contributions are always welcome!

* [Open an issue](https://github.com/weecology/forecasting-course/issues/new) to say Hi or if there’s anything we can do to help!
* Contributions of new lessons are welcome as Pull Requests or we can work with you to add new material and data to the site
* If you want to create a modified copy of the course including the website either follow the instructions for installing on Netlify above or fork/copy the repository and [connect it to Netlify](https://docs.netlify.com/welcome/add-new-site/) to automatically build the site.

For more information see our [CONTRIBUTING page](https://github.com/weecology/forecasting-course/tree/main/CONTRIBUTING.md)
