#!/usr/bin/env Rscript

# Generate the Schedule table from schedule/schedule.csv.
#
# Quarto runs this automatically before every render (see `pre-render` in
# _quarto.yml), so the published schedule can never drift from the CSV. It can
# also be run by hand:
#
#     Rscript scripts/build_schedule.R

root <- Sys.getenv("QUARTO_PROJECT_DIR", unset = ".")
csv_path <- file.path(root, "schedule", "schedule.csv")
out_path <- file.path(root, "schedule", "_schedule_table.md")

# --- helpers ---------------------------------------------------------------

# Strip one layer of matching quotes from a YAML scalar.
unquote <- function(value) {
  value <- trimws(value)
  if (nchar(value) >= 2) {
    first <- substr(value, 1, 1)
    last <- substr(value, nchar(value), nchar(value))
    if (first == last && first %in% c("\"", "'")) {
      return(substr(value, 2, nchar(value) - 1))
    }
  }
  value
}

# Escape a value for use inside a markdown table cell.
cell <- function(text) gsub("|", "\\|", text, fixed = TRUE)

# Pull a scalar field out of a page's YAML front matter.
#
# Deliberately a line-level read rather than a YAML parse so the build needs no
# packages.
front_matter_field <- function(lines, field) {
  if (length(lines) == 0 || trimws(lines[1]) != "---") return(NA_character_)
  closing <- which(trimws(lines[-1]) == "---")
  if (length(closing) == 0) return(NA_character_)
  block <- lines[2:closing[1]]
  pattern <- paste0("^", field, ":[ \t]*(.+?)[ \t]*$")
  hit <- grep(pattern, block, value = TRUE)
  if (length(hit) == 0) return(NA_character_)
  unquote(sub(pattern, "\\1", hit[1]))
}

# Map lesson title -> list(href, description) for every lesson page.
lesson_index <- function() {
  paths <- sort(Sys.glob(file.path(root, "lessons", "*", "index.qmd")))
  index <- list()
  for (path in paths) {
    lines <- readLines(path, warn = FALSE)
    title <- front_matter_field(lines, "title")
    if (is.na(title) || !nzchar(title)) next
    description <- front_matter_field(lines, "description")
    if (is.na(description)) description <- ""
    rel <- sub(paste0("^", normalizePath(root, mustWork = FALSE), "/?"), "",
               normalizePath(path, mustWork = FALSE))
    index[[title]] <- list(href = paste0("/", rel), description = description)
  }
  index
}

# --- main ------------------------------------------------------------------

lessons <- lesson_index()
rows <- read.csv(csv_path, stringsAsFactors = FALSE, colClasses = "character")

errors <- character(0)
lines_out <- c("| Date | Topic | Description |",
               "|------|-------|-------------|")

for (i in seq_len(nrow(rows))) {
  line_no <- i + 1  # +1 for the CSV header, to match what an editor shows
  date <- trimws(rows$date[i])
  title <- trimws(rows$lesson[i])
  kind <- trimws(rows$kind[i])
  if (!nzchar(kind)) kind <- "lesson"

  if (!nzchar(date) || !nzchar(title)) {
    errors <- c(errors, sprintf("schedule.csv line %d: missing date or lesson", line_no))
    next
  }

  if (kind == "event") {
    topic <- cell(title)
    description <- ""
  } else if (!is.null(lessons[[title]])) {
    entry <- lessons[[title]]
    topic <- sprintf("[%s](%s)", cell(title), entry$href)
    description <- cell(entry$description)
  } else {
    errors <- c(errors, sprintf(
      paste0("schedule.csv line %d: no lesson page titled '%s'. Fix the title to ",
             "match a lesson's `title:` exactly, or set kind=event."),
      line_no, title))
    next
  }

  lines_out <- c(lines_out, sprintf("| %s | %s | %s |", cell(date), topic, description))
}

if (length(errors) > 0) {
  message("Schedule build failed:")
  for (e in errors) message("  - ", e)
  quit(status = 1)
}

lines_out <- c(lines_out, "", ": {.schedule-table tbl-colwidths=\"[14,34,52]\"}")

writeLines(
  c("<!-- Generated by scripts/build_schedule.R from schedule.csv. Do not edit. -->",
    "",
    lines_out),
  out_path
)

message(sprintf("wrote schedule/_schedule_table.md (%d rows)", nrow(rows)))
